name: CI Pipeline

on:
  push:
    branches:
      - '**'   # Runs on push to any branch
  pull_request:
    branches:
      - main   # Runs on pull requests targeting the main branch

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'  # Only run unit tests on push events
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt

      - name: Run unit tests
        run: |
          python -m pytest tests/unit

  integration-tests:
    runs-on: ubuntu-latest
    if: github.event_name == 'pull_request'  # Only run integration tests on PR merges
    env:
      AWS_SAM_STACK_NAME: ${{ vars.AWS_SAM_STACK_NAME }}
      REGION: ${{ vars.REGION }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'  # Specify your Python version

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
          
      - name: Set up AWS CLI
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: $REGION

      - name: Deploy SAM application
        run: |
          sam deploy --stack-name $AWS_SAM_STACK_NAME --no-confirm-changeset --capabilities CAPABILITY_IAM

      - name: Run integration tests
        run: |
          python -m pytest tests/integration

      - name: Teardown SAM application
        if: always()
        run: |
          sam delete --stack-name $AWS_SAM_STACK_NAME --no-prompts
